### ISSUE TITLE
Remove reliance on Foundation

### ISSUE THREAD

**Issue by RSNara** [parasitic/hearthnet#15]
Here's how I think we should tackle this issue:
- [ ] pick a grid framework (either neat or jeet)
- [ ] remove foundation
- [ ] install scss
- [ ] install bourbon, neat/jeet
- [ ] redo all styles

**Comment by clemmy** [comment]
Not feeling bitters and refills?

**Comment by RSNara** [comment]
What?

**Comment by clemmy** [comment]
Fixed in 0d3819f1e70eb247b4f6a59692997797e8ff1687
